# Generated by Django 5.2.2 on 2025-06-24 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissionais', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissionalsaude',
            old_name='conselho',
            new_name='crm',
        ),
    ]
