# Generated by Django 5.2.2 on 2025-06-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='data_nascimente',
            new_name='data_nascimento',
        ),
    ]
