# Generated by Django 5.2.2 on 2025-06-06 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultas', '0002_initial'),
        ('profissionais', '0001_initial'),
        ('suprimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissionalsaude'),
        ),
        migrations.AddField(
            model_name='consultasuprimento',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.consulta'),
        ),
        migrations.AddField(
            model_name='consultasuprimento',
            name='suprimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suprimentos.suprimento'),
        ),
    ]
